# Copyright 2020 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# References:
# https://developer.github.com/webhooks/event-payloads/
# https://github.com/actions/cache
# https://github.com/actions/checkout
# https://github.com/actions/setup-python
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions/
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on: [push, pull_request]
name: Run tests
jobs:
  test_all:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: "${{matrix.os}}"
    name: "esphome run on ${{matrix.os}}"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 'Cache: .venv'
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('setup.sh', 'requirements.txt') }}
        restore-keys: ${{ runner.os }}-venv-
    - name: 'Cache: .esphome'
      uses: actions/cache@v1
      with:
        path: .esphome
        key: ${{ runner.os }}-esphome-${{ hashFiles('*.yaml', '*.txt') }}
        restore-keys: ${{ runner.os }}-esphome-
    - name: "./setup.sh (posix)"
      if: always() && matrix.os != 'windows-latest'
      run: ./setup.sh
    - name: "setup (windows)"
      if: always() && matrix.os == 'windows-latest'
      run: |
        pip3 install -q -U -r requirements.txt
    - name: "copy secrets (posix)"
      if: always() && matrix.os != 'windows-latest'
      run: |
        cp secrets.yaml.sample secrets.yaml
    - name: "copy secrets (windows)"
      if: always() && matrix.os == 'windows-latest'
      run: |
        copy secrets.yaml.sample secrets.yaml
    - name: "esphome compile (posix)"
      if: always() && matrix.os != 'windows-latest'
      run: |
        source .venv/bin/activate
        esphome emperor1510.yaml compile
    - name: "esphome compile (windows)"
      if: always() && matrix.os == 'windows-latest'
      run: |
        esphome emperor1510.yaml compile
