# Copyright 2020 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# References:
# https://developer.github.com/webhooks/event-payloads/
# https://github.com/actions/cache
# https://github.com/actions/checkout
# https://github.com/actions/setup-python
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions/
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on: [push, pull_request]
name: Run tests
jobs:
  test_all:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: "${{matrix.os}}"
    name: "pio run on ${{matrix.os}}"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 'Cache: .venv'
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('install_platformio.sh') }}
        restore-keys: ${{ runner.os }}-venv-
    - name: 'Cache: .pio'
      uses: actions/cache@v1
      with:
        path: .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
        restore-keys: ${{ runner.os }}-pio-
    # Technically, this could be "pip install pio" but I want to make sure the
    # setup script works.
    - name: "Setup"
      run: ./install_platformio.sh
    - name: "pio run"
      run: |
        source .venv/bin/activate
        pio run
